---
-   name: Dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes

-   name: GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

-   name: Fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

-   name: Repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
      update_cache: yes

-   name: Docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    notify: Start docker on boot

-   name: Periodic Docker prune
    cron:
      name: docker-prune
      job: 'docker system prune -af --filter "until=$((5*24))h"'
      minute: '0'
      hour: '1'

-   name: Remove useless packages
    apt:
      autoclean: yes

-   name: Remove useless dependencies
    apt:
      autoremove: yes